helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
Corrects the ingress URL's for preprod and prod.  Dev is already done.
=> BAVL-10 correct ingress urls in the preprod and prod helm config.

README.md, assets/js/card.js, assets/scss/application.scss, assets/scss/components/_card.scss, docker-compose-local.yml, integration_tests/pages/index.ts, server/routes/index.test.ts, server/utils/nunjucksSetup.ts, server/views/components/card.njk, server/views/pages/index.njk, server/views/partials/header.njk
Replicated homepage for BVL with card / tiles and content.
Add docker-compose-local.yml - for Redis container.
Update local running instructions against DEV.
=> BAVL-72: Replicate BVL homepage tiles and update local running instructions.

integration_tests/mockApis/bookAVideoLinkApi.ts, server/@types/bookAVideoLinkApi/index.d.ts, server/data/bookAVideoLinkApiClient.test.ts, server/data/bookAVideoLinkApiClient.ts
Using new endpoints for enabled courts and probation teams.  The old endpoints have been deprecated.
=> BAVL-298 using new replacement endpoints for enabled courts and probation teams.

server/views/pages/bookAVideoLink/checkBooking.njk, server/views/pages/bookAVideoLink/confirmation.njk, server/views/pages/bookAVideoLink/newBooking.njk
=> BAVL-321 change to video link URL labels to be Court and Probation specific.

server/routes/journeys/bookAVideoLink/handlers/newBookingHandler.test.ts, server/routes/journeys/bookAVideoLink/handlers/newBookingHandler.ts
https://github.com/user-attachments/assets/e80602b3-1979-4431-a184-3a018efb0cd9
=> BAVL-474: Fix issue where the journey object is undefined when entering the journey via the "Add another" button on the cancellation confirmation page

server/routes/journeys/admin/handlers/viewPrisonRoomHandler.ts, server/views/pages/admin/viewPrisonLocations.njk, server/views/pages/admin/viewPrisonRoom.njk, server/views/pages/admin/viewPrisons.njk
Refactoring mainly - implementing Jess designs for the room admin.
Still lots to decide - hence no tests as yet. 
This is for playback and iteration purposes.
=> BAVL-621: update admin designs

server/routes/journeys/admin/handlers/addRoomScheduleHandler.test.ts, server/routes/journeys/admin/handlers/addRoomScheduleHandler.ts, server/routes/journeys/admin/handlers/deleteRoomScheduleHandler.test.ts, server/routes/journeys/admin/handlers/editRoomScheduleHandler.test.ts, server/routes/journeys/admin/handlers/editRoomScheduleHandler.ts, server/routes/journeys/admin/handlers/shared/roomAndScheduleRequestBody.ts, server/routes/journeys/admin/handlers/shared/roomFunctions.ts, server/routes/journeys/admin/handlers/shared/scheduleRequestBody.ts, server/routes/journeys/admin/handlers/viewPrisonRoomHandler.test.ts, server/routes/journeys/admin/handlers/viewPrisonRoomHandler.ts, server/routes/testutils/adminTestUtils.ts
Now the full tests are in place, the re-factoring was much easier and safer, so this PR contains
* Shared test utility functions
* Shared functions for processing requests
* Common methods / patterns
Looks like a lot of change - but probably best to look at the files rather than the diffs, as it was mainly reorganising into common functions and re-using them.
=> BAVL-612: Refactoring admin journeys and tests with shared functions and consistent patterns

server/@types/bookAVideoLinkApi/index.d.ts
PR raised on the back of API PR [here](https://github.com/ministryofjustice/hmpps-book-a-video-link-api/pull/412).
=> BAVL-688 updating the types removing references to a deprecated one.

server/views/pages/admin/viewPrisons.njk
Missed back link going astray.
=> BAVL-727: Fix buglet in  back link on admin prison list

README.md, server/routes/journeys/bookAVideoLink/prisonerSearch/handlers/prisonerSearchResultsHandler.test.ts, server/views/pages/admin/viewPrisonLocations.njk, server/views/pages/bookAVideoLink/court/confirmation.njk
=> BAVL-731: Lowercase PVL links

server/@types/bookAVideoLinkApi/index.d.ts, server/routes/journeys/viewBooking/handlers/downloadCsvHandler.test.ts, server/routes/journeys/viewBooking/handlers/downloadCsvHandler.ts, server/views/pages/viewBooking/viewDailyBookings.njk
Probation team appointment CSV download from the view bookings screen.
=> BAVL-726 adding support for probation team appointment CSV download from the view bookings screen.

server/routes/journeys/viewBooking/handlers/viewDailyBookingsHandler.ts, server/views/pages/viewBooking/viewDailyBookings.njk
=> BAVL-798 adding support for court appointment printing from the view bookings screen.

package-lock.json, package.json
=> BAVL-829 security patch for UI.

server/routes/journeys/viewBooking/handlers/viewBookingHandler.test.ts, server/views/pages/viewBooking/viewBooking.njk
=> BAVL-844 bringing the view booking page inline with others for court bookings.

server/routes/journeys/viewBooking/handlers/downloadCsvHandler.test.ts, server/routes/journeys/viewBooking/handlers/downloadCsvHandler.ts
Changes to order rows for court CSV extracts.
Associated appointments are grouped by booking and order by earliest start time and the prisoner name.  This means if we have two appointments (bookings) starting at the same time but for different prisoners then the bookings will be ordered naturally by prisoner name.
So for example booking A (for Jon) and B (for Fred) for different prisoners at the same time would see Fred's booking being shown first in the CSV.
=> BAVL-845 the order of court CSV extracts should be grouped by booking and ordered by earliest start time and prisoner name of the group bookings.

feature.env, helm_deploy/hmpps-book-a-video-link-ui/values.yaml, integration_tests/e2e/amendBooking.cy.ts, integration_tests/e2e/createBooking.cy.ts, integration_tests/mockApis/fixtures/bookAVideoLinkApi/bobSmithCourtBooking.json, integration_tests/pages/bookAVideoLink/checkBooking.ts, integration_tests/pages/bookAVideoLink/confirmation.ts, integration_tests/pages/bookAVideoLink/newBooking.ts, integration_tests/pages/bookAVideoLink/notesForStaff.ts, integration_tests/pages/bookAVideoLink/viewBooking.ts, server/@types/bookAVideoLinkApi/index.d.ts, server/config.ts, server/routes/journeys/bookAVideoLink/court/handlers/bookingDetailsHandler.test.ts, server/routes/journeys/bookAVideoLink/court/handlers/bookingDetailsHandler.ts, server/routes/journeys/bookAVideoLink/court/handlers/checkBookingHandler.test.ts, server/routes/journeys/bookAVideoLink/court/handlers/checkBookingHandler.ts, server/routes/journeys/bookAVideoLink/court/handlers/commentsHandler.ts, server/routes/journeys/bookAVideoLink/court/handlers/confirmationHandler.test.ts, server/routes/journeys/bookAVideoLink/court/journey.ts, server/routes/journeys/bookAVideoLink/court/middleware/initialiseJourney.ts, server/services/courtBookingService.test.ts, server/services/courtBookingService.ts, server/utils/nunjucksSetup.ts, server/views/pages/bookAVideoLink/court/bookingDetails.njk, server/views/pages/bookAVideoLink/court/checkBooking.njk, server/views/pages/bookAVideoLink/court/confirmation.njk, server/views/pages/bookAVideoLink/court/notesForStaff.njk, server/views/pages/viewBooking/viewBooking.njk
This PR covers all court journeys:
* Create
* Amend
* View
* Cancel
* Add/change notes or comments
Book
Amend
Change notes
Confirm
=> BAVL-782: Court journey public/private comments

server/@types/bookAVideoLinkApi/index.d.ts, server/routes/journeys/bookAVideoLink/court/handlers/checkBookingHandler.test.ts, server/routes/journeys/bookAVideoLink/probation/handlers/checkBookingHandler.test.ts
Updated API types.
Unskipped previously skipped tests in request handlers.
Re-tested all request journeys and email content with feature toggle on and off.
=> BAVL-897: Update API types and test for request a booking

server/views/pages/viewBooking/viewBooking.njk
=> BAVL-908 small consistency tweaks to the change links for comments.

integration_tests/e2e/createBooking.cy.ts, integration_tests/pages/bookAVideoLink/checkBooking.ts, server/views/pages/bookAVideoLink/court/checkBooking.njk
=> BAVL-858: Add change links

integration_tests/e2e/amendBooking.cy.ts, integration_tests/pages/bookAVideoLink/viewBooking.ts, server/views/pages/viewBooking/viewBooking.njk
=> BAVL-884: Add change links

integration_tests/e2e/amendBooking.cy.ts, server/views/pages/viewBooking/viewBooking.njk
Adds the 'Change' link for guest pin.
=> BAVL-884 adds the change link for the guest pin on the amend journey.

server/views/pages/bookAVideoLink/court/bookingDetails.njk
=> BAVL-960: Add hint text to CVP link

server/views/pages/bookAVideoLink/probation/checkBooking.njk, server/views/pages/bookAVideoLink/probation/confirmation.njk
=> BAVL-911: Update probation booking screen labels

server/routes/journeys/admin/handlers/extractPrisonRoomConfigHandler.test.ts, server/views/pages/admin/extractPrisonRoomConfig.njk
This PR only changes the wording shown on the intermediate page for the room configuration data download
=> BAVL-1000: update wording to new design.

server/views/partials/beforeContent.njk
=> BAVL-1025 service is now in beta and not alpha.
